version: "3.3"

services:
  gitbucket:
    container_name: gitbucket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080  # HTTP
      - 8443:8443  # HTTPS (Optionnal)
      - 29418:29418 # SSH  (Optionnal, disabled by default)
    volumes:
      - ./data:/gitbucket/gitbucket_data
    restart: unless-stopped
    
    # Both of these can be commented if you don't intend to use a shell in the container.
    tty: true
    stdin_open: true
